name: Specs
on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: ./src/ext/lexbor-c
          key: ${{ runner.os }}-lexbor-revision-${{ hashFiles('./src/ext/revision') }}
      - name: Build ext
        run: crystal src/ext/build_ext.cr
      - name: Run tests
        run: crystal spec
